name: Prebuild Firebase

on: [push]

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Create Firebase Service Account File
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: echo "$FIREBASE_SERVICE_ACCOUNT" > $HOME/firebase-service-account.json

    - name: Authenticate Firebase CLI
      run: firebase auth:import --project YOUR_PROJECT_ID --account $HOME/firebase-service-account.json

    - name: Initialize Firebase
      run: firebase init
